ORCA_CONFIG_DIR = '~/.orca/'

ORCA_DB_DBNAME = "orca_projects"
ORCA_DB_USERNAME = "orca"
ORCA_DB_PASSWORD = "orcapass"
ORCA_DB_HOSTNAME = "172.21.0.100"
ORCA_DB_PORT = 5432

ORCA_CVESEARCH_IP = "127.0.0.1"
ORCA_CVESEARCH_PORT = 5000

ORCA_PROJECTS = None  # Defined at runtime
